### ISSUE TITLE
About the model performance of diffnetplus

### ISSUE THREAD

**Issue by ll0ruc** [PeiJieSun/diffnet#36]
Hi, I run the diffnetplus code on yelp data, get HR=0.3676,NDCG=0.2274, which is consistent with the performance in paper. 
When I remove the user and item features by`self.fusion_user_embedding = self.user_embedding, self.fusion_item_embedding = self.item_embedding`. get HR=0.3104, NDCG=0.1877, which is lower than Diffnet++-nf in paper.  Are there any adjusted parameters when remove feature?

**Comment by PeiJieSun** [comment]
@lijunweiyhn I am not familiar with experiment settings of DiffNet++, you may ask the second author of DiffNet++ for help.

**Comment by ll0ruc** [comment]
@PeiJieSun Thank you for your suggestion.
I will ask @lijunweiyhn for help

**Comment by lijunweiyhn** [comment]
Many thanks for your attention to our work.

Because diffnet++ has more components than diffNet, after removing the
features, we adjust some parameters to regain a better performance, e.g.,
selection of activation function(but with the same number of GCN layers),
relative proportions of different weights(Graph att), etc. It is
recommended to make some modifications as needed and then observe the
impact of different changes on the results. Btw, it should be noted that
some training may fall into a local optimum and affect the final result, so
just test the results for several more times.

Anyway, hope it helps you, and feel free to contact us if you have any
problems.
